### ISSUE TITLE
Some more to add

### ISSUE THREAD

**Issue by petecooper** [drmonkeyninja/test-payment-cards#3]
https://developers.braintreepayments.com/reference/general/testing/php

Disclosure: I forked, attempted valiantly to merge these in and spent 20 minutes fighting with `td` line breaks and lack of `rowspan` in Markdown before a huffy ragequit.

So, yeah - have at, @drmonkeyninja - best of luck!

**Comment by drmonkeyninja** [comment]
Thanks @petecooper. I know Markdown isn't everyone's cup of tea, but it is widely used, particularly on GitHub which is why I opted to use it for this repository. 

I've not come across Braintree before, I've attempted to add the relevant numbers. Let me know if anything is incorrect/misinterpreted.
